# Generated by Django 3.1.5 on 2021-02-08 05:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_contract_no', models.CharField(max_length=16)),
                ('company', models.CharField(max_length=64)),
                ('status', models.CharField(max_length=16)),
                ('my_role', models.CharField(max_length=16)),
                ('buyer_name', models.CharField(max_length=64)),
                ('supplier_name', models.CharField(max_length=64)),
                ('reference_no', models.CharField(max_length=16)),
                ('total_price', models.CharField(max_length=16)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('last_update', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('currency', models.CharField(max_length=3)),
                ('inco_terms', models.CharField(max_length=3)),
                ('payment_terms', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('trade_contract_no', models.CharField(max_length=16)),
                ('uploader_role', models.CharField(max_length=16)),
                ('uploader_name', models.CharField(max_length=64)),
                ('carton_no', models.IntegerField(default=1)),
                ('quantity', models.IntegerField(null=True)),
                ('description',models.CharField(default='avocados', max_length=64)),
                ('date_taken',models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('predicted_image', models.ImageField(blank=True, upload_to='')),
                ('blemished_avocados', models.IntegerField(default=0)),
                ('unripe', models.IntegerField(default=0)),
                ('almost_ripe', models.IntegerField(default=0)),
                ('ripe', models.IntegerField(default=0)),
                ('overripe', models.IntegerField(default=0)),
                ('rotten', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[                
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_fruit_type', models.CharField(max_length=16)),
                ('sku_supplier', models.CharField(max_length=64)),
                ('sku_trader', models.CharField(max_length=64)),
                ('sku_buyer', models.CharField(max_length=64)),
                ('quantity_cartons', models.IntegerField()),
                ('total_sell_price', models.CharField(max_length=64)),
                ('currency', models.CharField(max_length=16)),
                ('trade_contract_no', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=64)),
                ('supplier', models.CharField(max_length=64)),
                ('total_price', models.CharField(max_length=64)),
                ('insurance_tier', models.CharField(max_length=64, null=True)),
                ('insurance_premium', models.IntegerField(default=0)),
                ('status', models.CharField(default='Pending', max_length=16)),
                ('created_date',models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_date',models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('trade_contract_no', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.CharField(max_length=64)),
                ('supplier', models.CharField(max_length=64)),
                ('quantity', models.IntegerField()),
                ('claim_amount', models.IntegerField()),
                ('settlement_status', models.CharField(default="Pending", max_length=16)),
                ('created_date',models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_date',models.DateTimeField(blank=True, null=True)),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('trade_contract_no', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Avocados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_contract_no', models.CharField(max_length=16)),
                ('role', models.CharField(max_length=16)),
                ('blemished_pc', models.DecimalField(max_digits=4, decimal_places=1, default=0)),
                ('unripe_pc', models.DecimalField(max_digits=4, decimal_places=1, default=0)),
                ('almost_ripe_pc', models.DecimalField(max_digits=4, decimal_places=1, default=0)),
                ('ripe_pc', models.DecimalField(max_digits=4, decimal_places=1, default=0)),
                ('overripe_pc', models.DecimalField(max_digits=4, decimal_places=1, default=0)),
                ('rotten_pc', models.DecimalField(max_digits=4, decimal_places=1, default=0)),
                ('total_blemished', models.IntegerField(default=0)),
                ('total_unripe', models.IntegerField(default=0)),
                ('total_almost_ripe', models.IntegerField(default=0)),
                ('total_ripe', models.IntegerField(default=0)),
                ('total_overripe', models.IntegerField(default=0)),
                ('total_rotten', models.IntegerField(default=0)),
                ('total_quantity', models.IntegerField(default=0)),
            ],
        ),
    ]
